/*! Code generated by Coframe AI Editor */
(()=>{var n=Symbol.for("JSX.Fragment");var e=document.querySelector(".hip-lp__card-dscrptn");e?(e.innerHTML="<b>What are you protecting?</b> House or Apartment - We'll match you with the best security system",window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):console.error("h3 element not found");})();
